version: '3'
services:
  backend:
    image: trieutruong30/websitebangiay
    container_name: trieutruong30.websitebangiay_backend
    restart: always
    ports:
      - 8000:8000
  frontend:
    image: trieutruong30/websitebangiay-client
    container_name: trieutruong30.websitebangiay_client
    restart: always
    ports:
      - 3000:80
  socket:
    image: trieutruong30/websitebangiay-socket
    container_name: trieutruong30.websitebangiay_socket
    restart: always
    ports:
      - 4000:4000