version: '3'
services:
  proxy:
    image: khactrieu99/websitebangiay-proxy
    container_name: websitebangiay_proxy
    # build:
    #   context: ./proxy
    #   dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80
    networks:
      - common-network
    depends_on:
      - backend
      - frontend
      - socket
  backend:
    image: khactrieu99/websitebangiay-backend
    container_name: websitebangiay_backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile-prod
    restart: always
    # ports:
    #   - 8000:8000
    networks:
      - common-network
  frontend:
    image: khactrieu99/websitebangiay-client
    container_name: websitebangiay_client
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile-prod
    restart: always
    # ports:
    #   - 3000:80
    networks:
      - common-network
  socket:
    image: khactrieu99/websitebangiay-socket
    container_name: websitebangiay_socket
    # build:
    #   context: ./socket
    #   dockerfile: Dockerfile
    restart: always
    # ports:
    #   - 4000:4000
    networks:
      - common-network
networks:
  common-network:
    driver: bridge